### ISSUE TITLE
 Cannot read property 'bindings' of null"

### ISSUE THREAD

**Issue by BrightBeacon** [mapbox/react-native-mapbox-ar#20]
{
	"type": "TransformError",
	"lineNumber": 0,
	"errors": [{
		"description": "node_modules/react-native/Libraries/react-native/react-native-implementation.js: Cannot read property 'bindings' of null",
		"lineNumber": 0
	}],
	"name": "SyntaxError",
	"message": "node_modules/react-native/Libraries/react-native/react-native-implementation.js: Cannot read property 'bindings' of null",
	"stack": "TypeError: Cannot read property 'bindings' of null\n    at Scope.moveBindingTo (/Users/apple/Documents/others/react-native-mapbox-ar/RNMapboxARDemo/node_modules/@babel/traverse/lib/scope/index.js:867:13)\n    at BlockScoping.updateScopeInfo (/Users/apple/Documents/others/react-native-mapbox-ar/RNMapboxARDemo/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)\n    at BlockScoping.run (/Users/apple/Documents/others/react-native-mapbox-ar/RNMapboxARDemo/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)\n    at PluginPass.BlockStatementSwitchStatementProgram (/Users/apple/Documents/others/react-native-mapbox-ar/RNMapboxARDemo/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)\n    at newFn (/Users/apple/Documents/others/react-native-mapbox-ar/RNMapboxARDemo/node_modules/@babel/traverse/lib/visitors.js:193:21)\n    at NodePath._call (/Users/apple/Documents/others/react-native-mapbox-ar/RNMapboxARDemo/node_modules/@babel/traverse/lib/path/context.js:53:20)\n    at NodePath.call (/Users/apple/Documents/others/react-native-mapbox-ar/RNMapboxARDemo/node_modules/@babel/traverse/lib/path/context.js:40:17)\n    at NodePath.visit (/Users/apple/Documents/others/react-native-mapbox-ar/RNMapboxARDemo/node_modules/@babel/traverse/lib/path/context.js:88:12)\n    at TraversalContext.visitQueue (/Users/apple/Documents/others/react-native-mapbox-ar/RNMapboxARDemo/node_modules/@babel/traverse/lib/context.js:118:16)"
}

**Comment by jcharbo** [comment]
@BrightBeacon just upgrade babel-preset-react-native to 5.0.2.
